Add Book Management Library System
Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

PS E:\react> git status
fatal: not a git repository (or any of the parent directories): .git
PS E:\react> cd frontendproj
PS E:\react\frontendproj> cd globcash
PS E:\react\frontendproj\globcash> git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/App.js
        deleted:    src/reactproj/business.js
        deleted:    src/reactproj/currency converter.js
        deleted:    src/reactproj/help.js
        deleted:    src/reactproj/login.js
        deleted:    src/reactproj/my first proj.js
        deleted:    src/reactproj/router.js
        deleted:    src/reactproj/style.css

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        src/reactproj/book.js
        src/reactproj/bookread.js
        src/reactproj/bookreadall.js
        src/reactproj/bookrouter.js
        src/reactproj/bookupdate.js
        src/reactproj/deletebook.js
        src/reactproj/filterbook.js
        src/reactproj/home.js
        src/reactproj/index.css
        src/reactproj/insert.css

no changes added to commit (use "git add" and/or "git commit -a")
PS E:\react\frontendproj\globcash> git add
Nothing specified, nothing added.
hint: Maybe you wanted to say 'git add .'?
hint: Disable this message with "git config set advice.addEmptyPathspec false"
PS E:\react\frontendproj\globcash> git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/App.js
        deleted:    src/reactproj/business.js
        deleted:    src/reactproj/currency converter.js
        deleted:    src/reactproj/help.js
        deleted:    src/reactproj/login.js
        deleted:    src/reactproj/my first proj.js
        deleted:    src/reactproj/router.js
        deleted:    src/reactproj/style.css

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        src/reactproj/book.js
        src/reactproj/bookread.js
        src/reactproj/bookreadall.js
        src/reactproj/bookrouter.js
        src/reactproj/bookupdate.js
        src/reactproj/deletebook.js
        src/reactproj/filterbook.js
        src/reactproj/home.js
        src/reactproj/index.css
        src/reactproj/insert.css

no changes added to commit (use "git add" and/or "git commit -a")
PS E:\react\frontendproj\globcash> git add .
warning: in the working copy of 'src/App.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/reactproj/index.css', LF will be replaced by CRLF the next time Git touches it
PS E:\react\frontendproj\globcash> git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   src/App.js
        new file:   src/reactproj/book.js
        new file:   src/reactproj/bookread.js
        new file:   src/reactproj/bookreadall.js
        new file:   src/reactproj/bookrouter.js
        new file:   src/reactproj/bookupdate.js
        deleted:    src/reactproj/business.js
        deleted:    src/reactproj/currency converter.js
        new file:   src/reactproj/deletebook.js
        new file:   src/reactproj/filterbook.js
        deleted:    src/reactproj/help.js
        new file:   src/reactproj/home.js
        new file:   src/reactproj/index.css
        new file:   src/reactproj/insert.css
        deleted:    src/reactproj/login.js
        deleted:    src/reactproj/my first proj.js
        deleted:    src/reactproj/router.js
        deleted:    src/reactproj/style.css

PS E:\react\frontendproj\globcash> git commit -m "Add Book Management Library System"
[main 7ab1bfb] Add Book Management Library System
 18 files changed, 1349 insertions(+), 1579 deletions(-)
 create mode 100644 src/reactproj/book.js
 create mode 100644 src/reactproj/bookread.js
 create mode 100644 src/reactproj/bookreadall.js
 create mode 100644 src/reactproj/bookrouter.js
 create mode 100644 src/reactproj/bookupdate.js
 delete mode 100644 src/reactproj/business.js
 delete mode 100644 src/reactproj/currency converter.js
 create mode 100644 src/reactproj/deletebook.js
 create mode 100644 src/reactproj/filterbook.js
 delete mode 100644 src/reactproj/help.js
 create mode 100644 src/reactproj/home.js
 create mode 100644 src/reactproj/index.css
 create mode 100644 src/reactproj/insert.css
 delete mode 100644 src/reactproj/login.js
 delete mode 100644 src/reactproj/my first proj.js
 delete mode 100644 src/reactproj/router.js
 delete mode 100644 src/reactproj/style.css
PS E:\react\frontendproj\globcash> git push origin main
To https://github.com/premnath10435/globecash.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/premnath10435/globecash.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS E:\react\frontendproj\globcash> git pull --rebase origin main
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 8), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (11/11), 3.29 KiB | 30.00 KiB/s, done.
From https://github.com/premnath10435/globecash
 * branch            main       -> FETCH_HEAD
   e74517a..e79f045  main       -> origin/main
CONFLICT (modify/delete): src/reactproj/business.js deleted in 7ab1bfb (Add Book Management Library System) and modified in HEAD.  Version HEAD of src/reactproj/business.js left in tree.
CONFLICT (modify/delete): src/reactproj/my first proj.js deleted in 7ab1bfb (Add Book Management Library System) and modified in HEAD.  Version HEAD of src/reactproj/my first proj.js left in tree.
error: could not apply 7ab1bfb... Add Book Management Library System
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 7ab1bfb... # Add Book Management Library System
	PS E:\react\frontendproj\globcash